---
- name: "Converge"
  hosts: "cicd-debian-12"
  tasks:

    - name: "Include labocbz.add_logrotate_confs"
      tags:
        - "labocbz.add_logrotate_confs"
      vars:
        add_logrotate_confs__files: "{{ inv_add_logrotate_confs__files }}"
      ansible.builtin.include_role:
        name: "labocbz.add_logrotate_confs"
